### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by wh0ruwh0carez** [squarefractal/encryptedweb#3]
EFForg released version .5. When will you release .5 on palemoon addon website?

**Comment by wh0ruwh0carez** [comment]
Also, you should add this github URL to https://addons.palemoon.org/extensions/privacy-and-security/encrypted-web/
to get more attention, if you are the owner of it.

**Comment by squarefractal** [comment]
The project is not dead but I've been fairly busy with real life and updates may be expected at the end of April.
