### ISSUE TITLE
RFE: Restartless install & upgrade?

### ISSUE THREAD

**Issue by TPS** [squarefractal/encryptedweb#4]
I know that https://github.com/EFForg/https-everywhere isn't, but I hope it is possible to make this fork restartless. Here are some helpful links from
* [Mozilla](https://developer.mozilla.org/en-US/Add-ons/How_to_convert_an_overlay_extension_to_restartless) 
* [AB+](https://adblockplus.org/blog/why-you-should-make-your-next-add-on-restartless)

**Comment by squarefractal** [comment]
Making the extension restartless is would require a lot of effort and quite a bit of changes in the code for only a little convenience; so there are no plans to make this extension restartless.
